pipeline {
    agent any

    environment {
        GITHUB_TOKEN = credentials('github-token')
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', 
                    credentialsId: 'github-token', 
                    url: 'https://github.com/hoaroy/funori.git'
            }
        }
    }
}
