pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/hoaroy/funori.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat "npm install"
            }
        }

        stage('Run Security Scan') {
            steps {
                bat "npx snyk test"
            }
        }

        stage('Run Linter & Tests') {
            steps {
                bat "npm run lint"
                bat "npm test"
            }
        }
    }
}
