pipeline {
    agent any

    environment {
        NODEJS_HOME = tool 'NodeJS'
        PATH = "${NODEJS_HOME}/bin:${env.PATH}"
        GITHUB_TOKEN = credentials('github-token')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', 
                    credentialsId: 'github-token', 
                    url: 'https://github.com/hoaroy/funori.git'
            }
        }
       // stage('Install Dependencies') {
        //    steps {
           //     powershell 'npm install'
            //}
        //}
        //stage('Run ESLint') {
         //   steps {
          //      powershell 'npx eslint .'
         //   }
       // }
        //stage('Run Tests') {
         //   steps {
          //      powershell 'npm test'
           // }
        //}
        stage('Static Analysis with Snyk') {
            steps {
                powershell 'npx snyk code test'
            }
        }
    }
}
